# Generated by Django 5.2.16 on 2026-08-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0807_webpushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="voice_video_enabled",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
