# Generated by Django 5.2.16 on 2026-08-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0810_voice_channels_are_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="is_lounge",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
