# Generated by Django 5.2.16 on 2026-08-06 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0811_stream_is_lounge"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoungeRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("is_private", models.BooleanField(db_default=False, default=False)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("first_joined_at", models.DateTimeField(default=None, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lounge_rooms",
                        to="zerver.stream",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["channel"], name="zerver_loun_channel_ad0c3c_idx")
                ],
            },
        ),
    ]
